source 'https://github.com/CocoaPods/Specs.git'

target 'LINStorage', :exclusive => true do
  pod "LINStorage", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LINStorage", :path => "../"

  
end
